### ISSUE TITLE
Messages count

### ISSUE THREAD

**Issue by manakao** [Afinogen/get-mail#5]
Доброго времени суток!
Настраиваю вашу библиотеку.
При вызове $pop3->countMessages(); получаю 4, на ящике как раз 4.
Запрашиваю чтение четвертой записи, читаю.

Новый вызов скрипта, запрашиваю кол-во записей, получаю 3, по факту на ящике записи 4.

Как получать всегда общее кол-во сообщений ?

**Comment by Afinogen** [comment]
Доброго времени суток!
К сожалению, в данный момент скрипт видит только непрочитанные на сервере сообщения. Хотя
для получения количества сообщений в почтовом ящике через протокол POP3 используется команда STAT:
`В ответ на вызов команды сервер выдаёт положительный ответ "+OK", за которым следует количество сообщений в почтовом ящике и их общий размер в символах. Сообщения, которые помечены для удаления не учитываются в ответе сервера.`
Почему прочитанные сообщения не видны я пока не знаю, возможно надо считать количество из ответа команды LIST.
Если на выходных будет время по экспериментирую с этим.

**Comment by manakao** [comment]
После вызова $pop3->removeMessage($id)
сообщение должно реально с сервера пропадать?
Если да то сейчас физически с сервера не удаляется.
Использую gmail.

**Comment by Afinogen** [comment]
Должно либо удаляться либо падать в корзину, зависит от сервера. 
После вызова removeMessage, сообщение остается во входящих?

**Comment by manakao** [comment]
Тут оказалось дело в настройках Gmail. Там необходимо выставить что записи можно удалять. Прощу прощенья. Я попробовал запрашивать LIST, после прочтения но не удаления письма. Все равно возвращает 0. Как победить пока не предполагаю.

**Comment by Afinogen** [comment]
Я себе пометку на будущее сделал - запилить такую фичу. Как быстро решать данную проблему я не знаю, надо мануалы к протоколу курить

**Comment by manakao** [comment]
На сколько реально адаптировать вашу библиотеку для работы с IMAP ?

**Comment by Afinogen** [comment]
У меня есть ветка https://github.com/Afinogen/get-mail/tree/protocol-imap
Давно еще делал, но не помню на чем остановился, вполне возможно что код рабочий, попробуйте.

**Comment by kopyrin** [comment]
А как быть с ящиком на Яндексе? То же не удаляет. Причем письма прочитанными не помечает. Читает по 2-3 раза одно и тоже. На Яндексе пишут переходите на IMAP

**Comment by Afinogen** [comment]
@kopyrin На выходных проверю, не тестировал работу с яндексом.

**Comment by Afinogen** [comment]
@kopyrin извиняюсь за долгий ответ, в настройках (Почта - Все настройки - Почтовые программы) нужно поставить галочки "С сервера pop.yandex.ru по протоколу POP3" и "При получении почты по POP3 письма в почтовом ящике Яндекс.Почты помечать как прочитанные".
Удаление почты и пометка прочитывания ставится после дисконекта.

В README добавил информацию по подключению.
